# Requete 2

# !!!! PENSER A CHANGER LE NUMERO DE COMPTER

Là il était à 1 (voir I.3) le suivant doit le mettre à 2 (voir I.5)

# !! Je n'ai juste pas mis l'index requete parce que je n'arrive pas à savoir à quel moment l'introduire. Mais je l'ai fait à la main pour l'avatar que je viens de créer.

In [1]:
import urllib.parse

domain = "51.91.251.0"
port = 3000
host = f"http://{domain}:{port}"
path = lambda x: urllib.parse.urljoin(host, x)

In [2]:
import numpy as np 
import random
import pandas as pd
import requests

In [109]:
http://51.91.251.0:3000/remaining-requests/12e1e6fc-456b-4738-ba59-b90c3386f583

SyntaxError: invalid syntax (<ipython-input-109-312af1d2eff9>, line 1)

In [3]:
user_id = '12e1e6fc-456b-4738-ba59-b90c3386f583'

# I.Liste pays et langues

In [4]:
language_list=['austrian', 'belgian', 'bulgarian', 'croatian', 'cypriot', 'czech', 'danish', 'dutch', 'estonian', 'finnish', 'french', 'german', 'greek', 'hungarian', 'irish', 'italian', 'latvian', 'lithuanian', 'luxembourgish', 'maltese', 'polish', 'portuguese', 'romanian', 'slovakian', 'slovene', 'spanish' ,'swedish']

city_list=['amsterdam', 'copenhagen', 'madrid', 'paris', 'rome', 'sofia', 'valletta', 'vienna','vilnius']

## I.1 Test nom avatar

In [5]:
#test
l=random.choice(language_list)
c=random.choice(city_list)
name= 'ema-'+l+'-'+c+'-avatar'+ str(num_depart)
name

NameError: name 'num_depart' is not defined

## I.2 Création des intervals de dates et de la liste avec les intervals

In [6]:
#Création des intervals de dates et de la liste avec les intervals
date_1=np.arange(1,16)
print(date_1)
date_2=np.arange(16,30)
print(date_2)
date_3=np.arange(30,45)
print(date_3)
date_list=[date_1,date_2,date_3]
print(date_list)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44]
[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]), array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]), array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])]


In [7]:
#test
d=random.choice(date_list)
print(d)
a=random.sample(list(d),3)
a.sort(reverse=True)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[9, 8, 1]


## I.3 Numéro de l'avartar qu'on va créer mtn

In [8]:
compter=2 #numéro da l'avatar créé à augmenter à chaque nouvel avatar

## I.4 Liste des requetes

In [1867]:
compter

118

In [1868]:
requests_list=[]

#CREATION AVATAR
language=random.choice(language_list) # sélection d'une langue
city=random.choice(city_list) # sélection d'une ville
name = 'ema-'+language+'-'+city+'-avatar'+str(compter) # créé un nom d'avatar
print("name"+name)
r = requests.post(path(f'avatars/{user_id}/{name}'))
r = requests.get(path(f"avatars/{user_id}"))
for avatar in r.json():
    print(avatar['id'], avatar['name'])
    
    
compter+=1

nameema-danish-sofia-avatar118
6217 ema-first-avatar
34250 ema-austrian1-avatar
34256 ema-belgian1-avatar
34257 ema-bulgarian1-avatar
34258 ema-croatian1-avatar
34305 ema-german1-avatar
34259 ema-cypriot1-avatar
34260 ema-czech1-avatar
34264 ema-finnish1-avatar
34265 ema-french1-avatar
34261 ema-danish1-avatar
34262 ema-dutch1-avatar
34263 ema-estanian1-avatar
34429 ema-greek1-avatar
34457 ema-irish1-avatar
34455 ema-hungarian2-avatar
34456 ema-hungarian3-avatar
34458 ema-italian1-avatar
35123 ema-belgian3-avatar
37849 ema-luxembourgish1-avatar
38438 ema-luxembourgish2-avatar
73369 ema-maltese1-avatar
73371 ema-polish2-avatar
73370 ema-polish1-avatar
92219 ema-irish2-avatar
92220 ema-italian2-avatar
92221 ema-latvian1-avatar
92222 ema-lithuanian1-avatar
95016 ema-portuguese1-avatar
95247 ema-romanian1-avatar
95248 ema-slovakian1-avatar
95249 ema-slovene1-avatar
95250 ema-spanish1-avatar
95251 ema-swedish1-avatar
96528 ema-austrian2-avatar
96530 ema-cypriot2-avatar
96532 ema-danish2-ava

## I.5 Numero du prochain avatar (il faut le change dans I.3)

In [1869]:
compter # numéro de l'avatar suivant

119

## I.6 Trois dates sélectionnées

In [1870]:
# CHOIX DATE
date=random.choice(date_list) # choix d'un intervalle de temps
details_date=random.sample(list(date),5) # choix de 3 dates dans cet interval
details_date.sort(reverse = True) # classement des dates par ordre croissant
print(details_date)   

[14, 13, 8, 6, 2]


# II. Ajout des requetes dans la requests_list

In [1871]:
#AJOUT DE L AVATAR ET SES REQUETES A REQUESTS_LIST
for date in (details_date) : 
        params = {
            "avatar_name": name,
            "language": language,
            "city": city,
            "date": date,
            "mobile": np.random.randint(0,2),
        }
        print(params)
        r = requests.get(path(f"pricing/{user_id}"), params=params)
        r.json()
        
        requests_list.append(r)
       

{'avatar_name': 'ema-danish-sofia-avatar118', 'language': 'danish', 'city': 'sofia', 'date': 14, 'mobile': 1}
{'avatar_name': 'ema-danish-sofia-avatar118', 'language': 'danish', 'city': 'sofia', 'date': 13, 'mobile': 0}
{'avatar_name': 'ema-danish-sofia-avatar118', 'language': 'danish', 'city': 'sofia', 'date': 8, 'mobile': 0}
{'avatar_name': 'ema-danish-sofia-avatar118', 'language': 'danish', 'city': 'sofia', 'date': 6, 'mobile': 1}
{'avatar_name': 'ema-danish-sofia-avatar118', 'language': 'danish', 'city': 'sofia', 'date': 2, 'mobile': 1}


In [1872]:
## Test automatisation pour faire plusieurs requetes 


In [1873]:
#INDEX REQUETE

## Fait dans partie modele 

# III. BUILDING TEST

In [1874]:
# BUILDING TEST

pricing_requests = []

for r in requests_list:
    pricing_requests.append(
        pd.DataFrame(r.json()['prices']).assign(**r.json()['request'])
    )

pricing_requests = pd.concat(pricing_requests)
pricing_requests.head()

hotel_id  price  stock   city  date language  mobile  avatar_id
0       143     63     23  sofia    14   danish       1     158595
1       107     51      4  sofia    14   danish       1     158595
2       141     94     10  sofia    14   danish       1     158595
3       554     49      0  sofia    14   danish       1     158595
4       337    107     12  sofia    14   danish       1     158595

In [1875]:
pricing_requests

hotel_id  price  stock   city  date language  mobile  avatar_id
0        143     63     23  sofia    14   danish       1     158595
1        107     51      4  sofia    14   danish       1     158595
2        141     94     10  sofia    14   danish       1     158595
3        554     49      0  sofia    14   danish       1     158595
4        337    107     12  sofia    14   danish       1     158595
..       ...    ...    ...    ...   ...      ...     ...        ...
47       304     92      8  sofia     2   danish       1     158595
48       871     98      0  sofia     2   danish       1     158595
49       109    104      2  sofia     2   danish       1     158595
50       814    263      2  sofia     2   danish       1     158595
51        44     62      0  sofia     2   danish       1     158595

[269 rows x 8 columns]

# IV. MONTAGE DU DATA TRAIN

In [1876]:
data=pd.read_csv('./Datatrain/TRAIN_requete2.csv')
data=data.drop(['Unnamed: 0'],axis=1)
data

hotel_id  price  stock      city  date  language  mobile  avatar_id  \
0           639    149    110  valletta    35     greek       1     155054   
1           376    159    115  valletta    35     greek       1     155054   
2           985     68     70  valletta    35     greek       1     155054   
3           377    127     84  valletta    35     greek       1     155054   
4           200    130     80  valletta    35     greek       1     155054   
...         ...    ...    ...       ...   ...       ...     ...        ...   
35863       209     72     52  valletta    31  estonian       0     158594   
35864       360    164     71  valletta    31  estonian       0     158594   
35865       424    168     81  valletta    31  estonian       0     158594   
35866       404    142     22  valletta    31  estonian       0     158594   
35867       480     71     24  valletta    31  estonian       0     158594   

       index_request  
0                1.0  
1                1.0  
2                1.0  
3                1.0  
4                1.0  
...              ...  
35863            NaN  
35864            NaN  
35865            NaN  
35866            NaN  
35867            NaN  

[35868 rows x 9 columns]

In [1877]:
pricing_requests=pd.concat([data,pricing_requests])
pricing_requests

hotel_id  price  stock      city  date language  mobile  avatar_id  \
0        639    149    110  valletta    35    greek       1     155054   
1        376    159    115  valletta    35    greek       1     155054   
2        985     68     70  valletta    35    greek       1     155054   
3        377    127     84  valletta    35    greek       1     155054   
4        200    130     80  valletta    35    greek       1     155054   
..       ...    ...    ...       ...   ...      ...     ...        ...   
47       304     92      8     sofia     2   danish       1     158595   
48       871     98      0     sofia     2   danish       1     158595   
49       109    104      2     sofia     2   danish       1     158595   
50       814    263      2     sofia     2   danish       1     158595   
51        44     62      0     sofia     2   danish       1     158595   

    index_request  
0             1.0  
1             1.0  
2             1.0  
3             1.0  
4             1.0  
..            ...  
47            NaN  
48            NaN  
49            NaN  
50            NaN  
51            NaN  

[36137 rows x 9 columns]

In [1878]:
pricing_requests.to_csv('./Datatrain/TRAIN_requete2.csv')

# V. MONTAGE DU DATA TRAIN AVEC FEATURES

In [1879]:

hotels = pd.read_csv('features_hotels.csv', index_col=['hotel_id', 'city'])
pricing_requests = pricing_requests.join(hotels, on=['hotel_id', 'city'])
pricing_requests.head()

hotel_id  price  stock      city  date language  mobile  avatar_id  \
0       639    149    110  valletta    35    greek       1     155054   
1       376    159    115  valletta    35    greek       1     155054   
2       985     68     70  valletta    35    greek       1     155054   
3       377    127     84  valletta    35    greek       1     155054   
4       200    130     80  valletta    35    greek       1     155054   

   index_request         group           brand  parking  pool  children_policy  
0            1.0      Yin Yang     Royal Lotus        0     1                0  
1            1.0  Accar Hotels         Marcure        0     0                0  
2            1.0   Independant     Independant        1     0                0  
3            1.0  Boss Western  J.Halliday Inn        1     0                0  
4            1.0  Boss Western  J.Halliday Inn        0     0                0

In [1880]:
pricing_requests.to_csv('./Datatrain/TRAIN_requete2_features.csv')

In [1881]:
hotels = pd.read_csv('features_hotels.csv', index_col=['hotel_id', 'city'])